### ISSUE TITLE
[bug 🐞]: Failed to build docker image 

### ISSUE THREAD

**Issue by srealmoreno** [krrskl/flutter-dev-environment-docker#1]
### The docker image build fails at step:

```dockerfile
# Verify the status licenses
RUN yes | flutter doctor --android-licenses
```

<details>
<summary> Output </summary>

```bash
=> ERROR [dev_container_auto_added_stage_label 15/16] RUN yes | flutter  85.8s


                                                                                
------
 > [dev_container_auto_added_stage_label 15/16] RUN yes | flutter doctor --android-licenses:
#0 1.190    Woah! You appear to be trying to run flutter as root.
#0 1.191    We strongly recommend running the flutter tool without superuser privileges.
#0 1.191   /
#0 1.193 📎
#0 1.391 Downloading Linux x64 Dart SDK from Flutter engine 5fb3179a19c3e7dcb96c312b327c712ba9c77ec9...
#0 2.033   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#0 2.033                                  Dload  Upload   Total   Spent    Left  Speed
#0 2.033 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  205M    0 60304    0     0  83625      0  0:43:01 --:--:--  0:43:01 83639
  4  205M    4 10.1M    0     0  6042k      0  0:00:34  0:00:01  0:00:33 6042k
 11  205M   11 23.6M    0     0  8884k      0  0:00:23  0:00:02  0:00:21 8884k
 18  205M   18 37.2M    0     0  10.0M      0  0:00:20  0:00:03  0:00:17 10.0M
 24  205M   24 50.7M    0     0  10.7M      0  0:00:19  0:00:04  0:00:15 10.7M
 31  205M   31 64.2M    0     0  11.2M      0  0:00:18  0:00:05  0:00:13 12.8M
 36  205M   36 75.8M    0     0  11.2M      0  0:00:18  0:00:06  0:00:12 13.1M
 43  205M   43 89.4M    0     0  11.5M      0  0:00:17  0:00:07  0:00:10 13.1M
 50  205M   50  103M    0     0  11.8M      0  0:00:17  0:00:08  0:00:09 13.1M
 56  205M   56  116M    0     0  11.9M      0  0:00:17  0:00:09  0:00:08 13.1M
 63  205M   63  130M    0     0  12.1M      0  0:00:16  0:00:10  0:00:06 13.1M
 68  205M   68  141M    0     0  12.0M      0  0:00:17  0:00:11  0:00:06 13.1M
 75  205M   75  155M    0     0  12.1M      0  0:00:16  0:00:12  0:00:04 13.1M
 81  205M   81  168M    0     0  12.2M      0  0:00:16  0:00:13  0:00:03 13.1M
 88  205M   88  182M    0     0  12.3M      0  0:00:16  0:00:14  0:00:02 13.1M
 94  205M   94  195M    0     0  12.4M      0  0:00:16  0:00:15  0:00:01 12.9M
100  205M  100  205M    0     0  12.4M      0  0:00:16  0:00:16 --:--:-- 13.3M
[2023-05-18T22:25:11.626Z] 
#0 25.81 Building flutter tool...
#0 26.11 Resolving dependencies...
#0 37.33 Got dependencies.
#0 70.28 Downloading Material fonts...                                    1,167ms
#0 71.54 Downloading Gradle Wrapper...                                      176ms
#0 71.82 Downloading package sky_engine...                                  357ms
#0 72.25 Downloading flutter_patched_sdk tools...                           576ms
#0 72.95 Downloading flutter_patched_sdk_product tools...                   469ms
#0 73.55 Downloading linux-x64 tools...                                   2,704ms
[2023-05-18T22:25:11.627Z] 
#0 77.38 Downloading linux-x64/font-subset tools...                         351ms
#0 79.82 Error: A JNI error has occurred, please check your installation and try again
#0 79.82 Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/prefs/AndroidLocationsProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
#0 79.83 	at java.lang.ClassLoader.defineClass1(Native Method)
#0 79.83 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
#0 79.83 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
#0 79.83 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
#0 79.83 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
#0 79.83 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
#0 79.83 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
#0 79.83 	at java.security.AccessController.doPrivileged(Native Method)
[2023-05-18T22:25:11.629Z] #0 79.83 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
#0 79.83 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
#0 79.83 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
#0 79.83 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
#0 79.83 	at java.lang.Class.getDeclaredMethods0(Native Method)
#0 79.83 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
#0 79.83 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
#0 79.83 
[2023-05-18T22:25:11.631Z] 	at java.lang.Class.getMethod0(Class.java:3018)
#0 79.83 	at java.lang.Class.getMethod(Class.java:1784)
#0 79.83 	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:670)
#0 79.83 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:652)
#0 79.84 Android sdkmanager tool was found, but failed to run (/home/root/Android/sdk/cmdline-tools/latest/bin/sdkmanager): "exited code 1".
#0 79.84 Try re-installing or updating your Android SDK,
#0 79.84 visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.
------
Dockerfile-with-features:45
[2023-05-18T22:25:11.634Z] 
[2023-05-18T22:25:11.635Z] --------------------
  43 |     
  44 |     # Verify the status licenses
  45 | >>> RUN yes | flutter doctor --android-licenses
  46 |     
[2023-05-18T22:25:11.639Z] 
  47 |     # Start the adb daemon
--------------------
Exit code 1

```
</details>

Apparently in flutter jdk>=11 is required but the android sdk only supports jdk=8

**Comment by arbh89** [comment]
This is my updated version that works.

FROM ubuntu:22.04

# Arguments and environment variables
ARG BUILD_TOOLS_VERSION=34.0.0
ARG PLATFORM_VERSION=33
ARG COMMAND_LINE_VERSION=latest

# Installing necessary dependencies
RUN apt update
RUN apt install -y curl git unzip openjdk-11-jdk wget

# Configuring the working directory and user to use
ARG USER=root
USER $USER
WORKDIR /home/$USER

# Prepare environment
ENV ANDROID_HOME Android/sdk
ENV ANDROID_SDK_TOOLS $ANDROID_HOME/cmdline-tools/tools

# Creating Android directories
RUN mkdir -p $ANDROID_HOME
RUN mkdir -p $ANDROID_HOME/cmdline-tools
RUN mkdir -p /root/.android && touch /root/.android/repositories.cfg

# Download Android SDK
RUN wget -O commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
RUN unzip commandlinetools.zip && rm commandlinetools.zip
RUN mv cmdline-tools $ANDROID_SDK_TOOLS

# Download Flutter SDK
RUN git clone https://github.com/flutter/flutter.git

# Download sdk build tools and platform tools
WORKDIR $ANDROID_SDK_TOOLS/bin
RUN yes | ./sdkmanager --licenses
RUN ./sdkmanager "build-tools;${BUILD_TOOLS_VERSION}" "platform-tools" "platforms;android-${PLATFORM_VERSION}" "sources;android-${PLATFORM_VERSION}"
RUN ./sdkmanager --install "cmdline-tools;${COMMAND_LINE_VERSION}"

# Setup PATH environment variable
ENV PATH $PATH:/home/$USER/$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/tools/bin:/home/$USER/flutter/bin

# Verify the status licenses
RUN yes | flutter doctor --android-licenses

# Start the adb daemon
RUN adb start-server

**Comment by techwithks** [comment]
i got this error

Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/sudarshan/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/sudarshan/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-632554c5-9c5e-40de-9f0f-2bb22a481a9b1700576427874 --workspace-folder /Users/sudarshan/flutter-dev-environment-docker --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/sudarshan/flutter-dev-environment-docker --id-label devcontainer.config_file=/Users/sudarshan/flutter-dev-environment-docker/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/sudarshan/flutter-dev-environment-docker/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --terminal-columns 80 --terminal-rows 30

**Comment by techwithks** [comment]
Not Working... 

45 |     # Verify the status licenses
  46 | >>> RUN yes | flutter doctor --android-licenses
  47 |     
  48 |     # Start the adb daemon
--------------------
ERROR: failed to solve: process "/bin/sh -c yes | flutter doctor --android-licenses" did not complete successfully: exit code: 1
[3218565 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/g1/qvsmy7d97kl8sm3yjqxw_qdw0000gn/T/devcontainercli/container-features/0.51.3-1700579904890/Dockerfile-with-features -t vsc-flutter-dev-environment-docker-f87f0b4bd7ad55d3328dcf1fdbe1e24667e19520b2dca70eedfb548908b7b989 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/sudarshan/flutter-dev-environment-docker
